spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micr-synch
    username: qwe
    password: qwe
    driver-class-name: org.postgresql.Driver
  flyway:
    user: qwe
    password: qwe
    url: jdbc:postgresql://localhost:5432/micr-synch
  application:
    name: order

server:
  port: 7003