spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/micr-synch
    username: qwe
    password: qwe

  application:
    name: order

server:
  port: 7003