spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/micr-synch}
    username: ${DB_USERNAME:qwe}
    password: ${DB_PASSWORD:qwe}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: ${APP_NAME:order}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

server:
  port: ${SERVER_PORT:7003}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
  instance:
    prefer-ip-address: true
